INSERT INTO users (name, age) VALUES ("Bob", 25);
INSERT INTO users (name, age) VALUES ("Jon", 35);
INSERT INTO users (name, age) VALUES ("Jen", 45);
INSERT INTO users (name, age) VALUES ("Jill", 37);
INSERT INTO users (name, age) VALUES ("Cole", 20);
INSERT INTO users (name, age) VALUES ("Jin", 39);
INSERT INTO users (name, age) VALUES ("Len", 55);
INSERT INTO users (name, age) VALUES ("Keith", 57);
INSERT INTO users (name, age) VALUES ("Tom", 25);
INSERT INTO users (name, age) VALUES ("Tina", 35);
INSERT INTO users (name, age) VALUES ("Lester", 45);
INSERT INTO users (name, age) VALUES ("Edith", 37);
INSERT INTO users (name, age) VALUES ("Ted", 20);
INSERT INTO users (name, age) VALUES ("Sara", 39);
INSERT INTO users (name, age) VALUES ("Joe", 55);
INSERT INTO users (name, age) VALUES ("Chris", 57);
INSERT INTO users (name, age) VALUES ("Jed", 20);
INSERT INTO users (name, age) VALUES ("Scott", 39);
INSERT INTO users (name, age) VALUES ("Ken", 55);
INSERT INTO users (name, age) VALUES ("Odi", 57);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Do", "Tech", 5000, 1.25, 2.25);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Rey", "Science", 1000, 2.25, 3.25);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Mi", "Writing", 15000, 1.23, 2.15);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Fa", "Science", 11000, 12.25, 3.2);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("So", "Sports", 25000, 11.25, 12.25);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("La", "Architecture", 211000, 4.25, 5.28);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ti", "Writing", 2000, 11.23, 3.15);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Da", "Science", 711000, 2.25, 7.2);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Meh", "Math", 90000, 6.23, 8.15);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Dah", "Science", 91000, 5.25, 7.2);

INSERT INTO pledges (amount, project_id, user_id) VALUES (40, 1, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (50, 2, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (100, 3, 4);
INSERT INTO pledges (amount, project_id, user_id) VALUES (500, 3, 6);
INSERT INTO pledges (amount, project_id, user_id) VALUES (409, 9, 9);
INSERT INTO pledges (amount, project_id, user_id) VALUES (505, 6, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1000, 3, 9);
INSERT INTO pledges (amount, project_id, user_id) VALUES (5000, 9, 15);
INSERT INTO pledges (amount, project_id, user_id) VALUES (4000, 7, 20);
INSERT INTO pledges (amount, project_id, user_id) VALUES (504, 8, 12);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1000, 3, 14);
INSERT INTO pledges (amount, project_id, user_id) VALUES (200, 5, 15);
INSERT INTO pledges (amount, project_id, user_id) VALUES (450, 10, 11);
INSERT INTO pledges (amount, project_id, user_id) VALUES (50, 6, 17);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 4, 19);
INSERT INTO pledges (amount, project_id, user_id) VALUES (2000, 9, 13);
INSERT INTO pledges (amount, project_id, user_id) VALUES (508, 2, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1005, 3, 14);
INSERT INTO pledges (amount, project_id, user_id) VALUES (5002, 2, 6);
INSERT INTO pledges (amount, project_id, user_id) VALUES (40, 3, 9);
INSERT INTO pledges (amount, project_id, user_id) VALUES (505, 10, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1000, 3, 18);
INSERT INTO pledges (amount, project_id, user_id) VALUES (500, 2, 15);
INSERT INTO pledges (amount, project_id, user_id) VALUES (400, 4, 20);
INSERT INTO pledges (amount, project_id, user_id) VALUES (300, 8, 16);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 8, 14);
INSERT INTO pledges (amount, project_id, user_id) VALUES (20, 5, 17);
INSERT INTO pledges (amount, project_id, user_id) VALUES (45, 10, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (50, 8, 17);
INSERT INTO pledges (amount, project_id, user_id) VALUES (105, 2, 19);
